# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.22]  # Add more Go versions if needed
        os: [linux, darwin]
        arch: [amd64, arm64]  # Add more architectures if needed
        
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build for ${{ matrix.os }} ${{ matrix.arch }}
      run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -v ./...

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: terraform-provider-rediskey_${{ matrix.os }}_${{ matrix.arch }}
        path: ./${{ matrix.os }}_${{ matrix.arch }}/terraform-provider-rediskey
